repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with cargo fmt
        entry: cargo fmt
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources with clippy
        entry: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
        args: ["--all-targets", "--all-features", "--", "-D", "warnings"]

