[package]
name = "sandbox"
version = "0.1.0"
authors = ["changhui lee <iam@xo.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.14"
nix = "0.21.0"
seccomp-sys = "0.1.3"

[features]
