languages:
  - name: c
    kind: compile
    compile:
      bin: /usr/bin/gcc
      args:
        ["gcc", "-O2", "-Wall", "-static", "-o", "<OUTPUT>", "<INPUT>", "-lm"]
    run:
      bin: "<TARGET>"
      args: ["<TARGET>"]

  - name: python
    kind: interpret
    run:
      bin: /usr/bin/python3
      args: ["python3", "<TARGET>"]
